name: "Post to Bluesky"

on:
  schedule: 
    - cron: "30 5,17 * * *"

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - name: Send post
        run: node index.js
        env:
          IDENTIFIER: ${{ secrets.IDENTIFIER }}
          PASSWORD: ${{ secrets.PASSWORD }}
